#!/bin/bash

set -e

version_ending="0"
if [ -n "$TRAVIS_BUILD_NUMBER" ]; then
  # see https://docs.travis-ci.com/user/environment-variables/
  version_ending="${TRAVIS_BUILD_NUMBER}"
fi

echo -n "1.0.$version_ending"
